if(NOT SRC_ROOT OR NOT OUT_DIR)
  message(FATAL_ERROR "GenTables.cmake needs -DSRC_ROOT=<repo> -DOUT_DIR=<dir>")
endif()

file(MAKE_DIRECTORY "${OUT_DIR}")

function(trim_hex out hex)
  string(TOUPPER "${hex}" hex)
  string(REGEX REPLACE "^0+([0-9A-F])" "\\1" hex "${hex}")
  set(${out} "${hex}" PARENT_SCOPE)
endfunction()

function(pad_hex out hex)
  string(TOUPPER "${hex}" hex)
  string(LENGTH "${hex}" len)
  while(len LESS 4)
    set(hex "0${hex}")
    math(EXPR len "${len} + 1")
  endwhile()
  set(${out} "${hex}" PARENT_SCOPE)
endfunction()

function(write_if_changed path content)
  set(old "")
  if(EXISTS "${path}")
    file(READ "${path}" old)
  endif()
  if(NOT old STREQUAL content)
    file(WRITE "${path}" "${content}")
  endif()
endfunction()

function(emit_unique_rows path rows_var count_var)
  set(rows "${${rows_var}}")
  list(SORT rows)
  list(REMOVE_DUPLICATES rows)
  set(out "")
  set(last "")
  set(count 0)
  foreach(row IN LISTS rows)
    string(REGEX REPLACE "^([0-9A-F]+)\\|(.*)$" "\\1" key "${row}")
    string(REGEX REPLACE "^([0-9A-F]+)\\|(.*)$" "\\2" line "${row}")
    if(NOT key STREQUAL last)
      set(last "${key}")
      math(EXPR count "${count} + 1")
      string(APPEND out "${line}\n")
    endif()
  endforeach()
  write_if_changed("${path}" "${out}")
  set(${count_var} ${count} PARENT_SCOPE)
endfunction()

file(READ "${SRC_ROOT}/include/enums.h" enums)
string(REGEX MATCH "typedef enum actor_e[^{]*{([^}]*)}" _ "${enums}")
set(actor_body "${CMAKE_MATCH_1}")
string(REGEX MATCHALL "ACTOR_[0-9A-Fa-f]+_[A-Za-z0-9_]+" actor_names "${actor_body}")

set(rows "")
foreach(name IN LISTS actor_names)
  string(REGEX REPLACE "^ACTOR_([0-9A-Fa-f]+)_(.+)$" "\\1" hex "${name}")
  string(REGEX REPLACE "^ACTOR_([0-9A-Fa-f]+)_(.+)$" "\\2" tail "${name}")
  pad_hex(key "${hex}")
  string(TOUPPER "${hex}" hex)
  list(APPEND rows "${key}|    {0x${hex}, \"${tail}\"},")
endforeach()
emit_unique_rows("${OUT_DIR}/ActorNames.inc" rows n_names)

string(REGEX MATCH "enum level_e[ \t\r\n]*{([^}]*)}" _ "${enums}")
string(REGEX MATCHALL "LEVEL_[0-9A-Fa-f]+_[A-Za-z0-9_]+" level_enum "${CMAKE_MATCH_1}")
set(rows "")
foreach(name IN LISTS level_enum)
  string(REGEX REPLACE "^LEVEL_([0-9A-Fa-f]+)_(.+)$" "\\1" hex "${name}")
  string(REGEX REPLACE "^LEVEL_([0-9A-Fa-f]+)_(.+)$" "\\2" tail "${name}")
  pad_hex(key "${hex}")
  list(APPEND rows "${key}|    { 0x${hex}, \"${tail}\" },")
endforeach()
emit_unique_rows("${OUT_DIR}/LevelEnum.inc" rows n_level_enum)

function(token_id out tok)
  string(STRIP "${tok}" tok)
  if(tok MATCHES "^(ACTOR|ASSET|MARKER)_([0-9A-Fa-f]+)_")
    set(${out} "${CMAKE_MATCH_2}" PARENT_SCOPE)
  elseif(tok MATCHES "^0[xX]([0-9A-Fa-f]+)$")
    set(${out} "${CMAKE_MATCH_1}" PARENT_SCOPE)
  elseif(tok MATCHES "^[0-9]+$")
    math(EXPR v "${tok}" OUTPUT_FORMAT HEXADECIMAL)
    string(REGEX REPLACE "^0[xX]" "" v "${v}")
    set(${out} "${v}" PARENT_SCOPE)
  else()
    set(${out} "" PARENT_SCOPE)
  endif()
endfunction()

file(READ "${SRC_ROOT}/src/core2/gccube.c" gccube)
string(FIND "${gccube}" "func_803084F0" exit_fn_pos)
set(rows "")
if(exit_fn_pos GREATER -1)
  string(SUBSTRING "${gccube}" ${exit_fn_pos} -1 exit_fn)
  string(FIND "${exit_fn}" "default:" exit_fn_end)
  if(exit_fn_end GREATER -1)
    string(SUBSTRING "${exit_fn}" 0 ${exit_fn_end} exit_fn)
  endif()
  string(REGEX MATCHALL "case[ \t]*(0[xX][0-9A-Fa-f]+|[0-9]+)[ \t]*:[ \t]*[A-Za-z0-9_]+[ \t]*=[ \t]*ACTOR_[0-9A-Fa-f]+_"
         exit_cases "${exit_fn}")
  foreach(one IN LISTS exit_cases)
    string(REGEX MATCH "case[ \t]*(0[xX][0-9A-Fa-f]+|[0-9]+)[ \t]*:[ \t]*[A-Za-z0-9_]+[ \t]*=[ \t]*ACTOR_([0-9A-Fa-f]+)_"
           _ "${one}")
    set(exit_tok "${CMAKE_MATCH_1}")
    set(actor_hex "${CMAKE_MATCH_2}")
    token_id(exit_hex "${exit_tok}")
    trim_hex(exit_hex "${exit_hex}")
    trim_hex(actor_hex "${actor_hex}")
    pad_hex(key "${exit_hex}")
    list(APPEND rows "${key}|    { 0x${exit_hex}, 0x${actor_hex} },")
  endforeach()
endif()
emit_unique_rows("${OUT_DIR}/ExitActors.inc" rows n_exits)
if(n_exits EQUAL 0)
  message(WARNING "editor tables: no exit-to-actor cases found in func_803084F0")
endif()

file(READ "${SRC_ROOT}/src/core2/map/warp_dispatch.c" warp_dispatch)
string(REGEX MATCH "sWarpFunctions[^=]*=[ \t\r\n]*[{]([^;]*)[}];" _ "${warp_dispatch}")
set(warp_table "${CMAKE_MATCH_1}")
string(REGEX REPLACE "//[^\n]*" "" warp_table "${warp_table}")
string(REGEX REPLACE "[(]CodeAD110Callback[)]" "" warp_table "${warp_table}")
string(REGEX MATCHALL "[A-Za-z_][A-Za-z0-9_]*" warp_names "${warp_table}")

file(READ "${SRC_ROOT}/src/core2/map/cutscene_skip.c" cutscene_skip)
string(REGEX MATCHALL "void[ \t\r\n]+warp_[A-Za-z0-9_]+[ \t\r\n]*[(][^)]*[)][ \t\r\n]*[{][ \t\r\n]*func_8031CC8C[ \t\r\n]*[(][ \t\r\n]*arg0[ \t\r\n]*,[ \t\r\n]*0x[0-9A-Fa-f]+[ \t\r\n]*[)][ \t\r\n]*;[ \t\r\n]*[}]" warp_bodies "${cutscene_skip}")
set(warp_handler_names "")
set(warp_handler_dests "")
foreach(body IN LISTS warp_bodies)
  string(REGEX MATCH "void[ \t\r\n]+(warp_[A-Za-z0-9_]+)" _ "${body}")
  set(handler "${CMAKE_MATCH_1}")
  string(REGEX MATCH "arg0[ \t\r\n]*,[ \t\r\n]*0x([0-9A-Fa-f]+)" _ "${body}")
  list(APPEND warp_handler_names "${handler}")
  list(APPEND warp_handler_dests "${CMAKE_MATCH_1}")
endforeach()

set(rows "")
set(slot 0)
foreach(name IN LISTS warp_names)
  list(FIND warp_handler_names "${name}" found)
  if(NOT found EQUAL -1)
    list(GET warp_handler_dests ${found} dest_hex)
    pad_hex(key "${slot}")
    list(APPEND rows "${key}|    { ${slot}, 0x${dest_hex} },")
  endif()
  math(EXPR slot "${slot} + 1")
endforeach()
emit_unique_rows("${OUT_DIR}/WarpDests.inc" rows n_warp_dests)
if(n_warp_dests EQUAL 0)
  message(WARNING "editor tables: no warp destinations found in cutscene_skip.c")
endif()

set(rows "")
set(slot 0)
foreach(name IN LISTS warp_names)
  if(name MATCHES "^warp_")
    pad_hex(key "${slot}")
    list(APPEND rows "${key}|    { ${slot}, \"${name}\" },")
  endif()
  math(EXPR slot "${slot} + 1")
endforeach()
emit_unique_rows("${OUT_DIR}/WarpNames.inc" rows n_warp_names)


set(rows "")
string(REGEX MATCHALL "ASSET_[0-9A-Fa-f]+_MODEL_SKYBOX_[A-Z0-9_]+" sky_names "${enums}")
string(REGEX MATCHALL "ASSET_[0-9A-Fa-f]+_MODEL_CLOUDS_[A-Z0-9_]+" cloud_names "${enums}")
list(APPEND sky_names ${cloud_names})
foreach(name IN LISTS sky_names)
  string(REGEX REPLACE "^ASSET_([0-9A-Fa-f]+)_MODEL_(.+)$" "\1" hex "${name}")
  pad_hex(key "${hex}")
  list(APPEND rows "${key}|    { 0x${hex}, \"${name}\" },")
endforeach()
emit_unique_rows("${OUT_DIR}/SkyModels.inc" rows n_sky)


file(GLOB_RECURSE csrc "${SRC_ROOT}/src/*.c")
set(rows "")
set(tok "[ \t\r\n]*([A-Za-z0-9_]+)[ \t\r\n]*")
foreach(f IN LISTS csrc)
  file(READ "${f}" text)
  if(NOT text MATCHES "ActorInfo")
    continue()
  endif()
  string(REGEX REPLACE "//[^\n]*" "" text "${text}")
  string(REGEX REPLACE "/\\*[^*]*\\*+([^/*][^*]*\\*+)*/" "" text "${text}")
  string(REGEX MATCHALL "ActorInfo[ \t\r\n]+[A-Za-z0-9_]+[ \t\r\n]*=[ \t\r\n]*{${tok},${tok},${tok},"
         infos "${text}")
  foreach(info IN LISTS infos)
    string(REGEX MATCH "ActorInfo[ \t\r\n]+([A-Za-z0-9_]+)" _ "${info}")
    set(sym "${CMAKE_MATCH_1}")
    string(REGEX MATCH "{${tok},${tok},${tok},$" _ "${info}")
    token_id(actor "${CMAKE_MATCH_2}")
    token_id(model "${CMAKE_MATCH_3}")
    if(actor STREQUAL "")
      continue()
    endif()
    trim_hex(actor_trimmed "${actor}")
    set(aid_${sym} "${actor_trimmed}")
    if(model STREQUAL "")
      continue()
    endif()
    pad_hex(key "${actor}")
    trim_hex(model "${model}")
    list(APPEND rows "${key}|    {0x${actor_trimmed}, 0x${model}},")
  endforeach()
endforeach()
emit_unique_rows("${OUT_DIR}/ActorModels.inc" rows n_models)

file(READ "${SRC_ROOT}/src/core2/map/mapModel.c" mapmodel)
string(REGEX REPLACE "//[^\n]*" "" mapmodel "${mapmodel}")
string(REGEX MATCH "MapModelDescription D_8036ABE0\\[\\] = {(.*)};" _ "${mapmodel}")
set(table_body "${CMAKE_MATCH_1}")
set(level_re "{MAP_([0-9A-Fa-f]+)_([A-Za-z0-9_]+),[ \t\r\n]*(ASSET_[0-9A-Fa-f]+_[A-Za-z0-9_]+|0)[ \t\r\n]*,[ \t\r\n]*(ASSET_[0-9A-Fa-f]+_[A-Za-z0-9_]+|0)[ \t\r\n]*,[ \t\r\n]*{([^}]*)}[ \t\r\n]*,[ \t\r\n]*{([^}]*)}[ \t\r\n]*,[ \t\r\n]*([0-9.]+)")
string(REGEX MATCHALL "${level_re}" level_rows "${table_body}")
set(out "")
set(count 0)
foreach(row IN LISTS level_rows)
  string(REGEX MATCH "${level_re}" _ "${row}")
  set(map_hex "${CMAKE_MATCH_1}")
  set(map_name "${CMAKE_MATCH_2}")
  set(opa_tok "${CMAKE_MATCH_3}")
  set(xlu_tok "${CMAKE_MATCH_4}")
  set(cube_min "${CMAKE_MATCH_5}")
  set(cube_max "${CMAKE_MATCH_6}")
  set(scale "${CMAKE_MATCH_7}")
  token_id(opa "${opa_tok}")
  token_id(xlu "${xlu_tok}")
  string(REGEX REPLACE "[ \t\r\n]" "" cube_min "${cube_min}")
  string(REGEX REPLACE "[ \t\r\n]" "" cube_max "${cube_max}")
  if(opa STREQUAL "" OR opa STREQUAL "0")
    continue()
  endif()
  if(xlu STREQUAL "")
    set(xlu "0")
  endif()
  if(NOT scale MATCHES "\\.")
    set(scale "${scale}.0")
  endif()
  trim_hex(map_hex "${map_hex}")
  trim_hex(opa "${opa}")
  trim_hex(xlu "${xlu}")
  math(EXPR count "${count} + 1")
  string(APPEND out "    { 0x${map_hex}, \"${map_name}\", 0x${opa}, 0x${xlu}, { ${cube_min} }, { ${cube_max} }, ${scale}f },\n")
endforeach()
write_if_changed("${OUT_DIR}/LevelModels.inc" "${out}")
set(n_levels ${count})
macro(collect_spawn_adds text_var overlay)
  string(REGEX MATCHALL "spawnableActorList_add[A-Za-z]*[ \t\r\n]*\\([ \t\r\n]*&[ \t\r\n]*[A-Za-z0-9_]+"
         adds "${${text_var}}")
  foreach(add IN LISTS adds)
    string(REGEX MATCH "&[ \t\r\n]*([A-Za-z0-9_]+)$" _ "${add}")
    set(sym "${CMAKE_MATCH_1}")
    if(DEFINED aid_${sym})
      pad_hex(key "${aid_${sym}}")
      list(APPEND spawn_rows "${overlay}${key}|    { 0x${overlay}, 0x${aid_${sym}} },")
    else()
      message(WARNING "editor tables: no ActorInfo found for spawnable '${sym}'")
    endif()
  endforeach()
endmacro()

set(spawn_rows "")
file(READ "${SRC_ROOT}/src/core2/spawnqueue.c" sq)
string(REGEX REPLACE "//[^\n]*" "" sq "${sq}")
string(REGEX REPLACE "/\\*[^*]*\\*+([^/*][^*]*\\*+)*/" "" sq "${sq}")
string(FIND "${sq}" "case OVERLAY_9_SNOW:" sq_cut)
if(sq_cut EQUAL -1)
  collect_spawn_adds(sq 0)
else()
  string(SUBSTRING "${sq}" 0 ${sq_cut} sq_common)
  string(SUBSTRING "${sq}" ${sq_cut} -1 sq_fp)
  collect_spawn_adds(sq_common 0)
  collect_spawn_adds(sq_fp 9)
endif()

foreach(pair IN ITEMS
    "CC/ccspawnqueue.c;2"
    "MMM/mmmspawnqueue.c;3"
    "GV/gvspawnqueue.c;4"
    "TTC/actor_spawninit.c;5"
    "MM/mmspawnqueue.c;6"
    "BGS/bgsspawnqueue.c;7"
    "RBB/rbbspawnqueue.c;8"
    "FP/fpspawnqueue.c;9"
    "CCW/ccwspawnqueue.c;A"
    "SM/smspawnqueue.c;B"
    "cutscenes/cutscenesspawnqueue.c;C"
    "lair/lairspawnqueue.c;D"
    "fight/fight.c;E")
  list(GET pair 0 rel)
  list(GET pair 1 ov)
  file(READ "${SRC_ROOT}/src/${rel}" text)
  string(REGEX REPLACE "//[^\n]*" "" text "${text}")
  string(REGEX REPLACE "/\\*[^*]*\\*+([^/*][^*]*\\*+)*/" "" text "${text}")
  collect_spawn_adds(text ${ov})
endforeach()

emit_unique_rows("${OUT_DIR}/SpawnSets.inc" spawn_rows n_spawn)
file(READ "${SRC_ROOT}/src/core2/map/overlay.c" ovsrc)
string(REGEX REPLACE "//[^\n]*" "" ovsrc "${ovsrc}")
string(REGEX MATCHALL "{[ \t\r\n]*LEVEL_([0-9A-Fa-f]+)_[A-Za-z0-9_]+,[ \t\r\n]*OVERLAY_([0-9A-Fa-f]+)_"
       ov_rows "${ovsrc}")
foreach(row IN LISTS ov_rows)
  string(REGEX MATCH "LEVEL_([0-9A-Fa-f]+)_[A-Za-z0-9_]+,[ \t\r\n]*OVERLAY_([0-9A-Fa-f]+)_" _ "${row}")
  string(TOUPPER "${CMAKE_MATCH_1}" lvl)
  string(TOUPPER "${CMAKE_MATCH_2}" ov)
  set(lvl2ov_${lvl} "${ov}")
endforeach()

file(READ "${SRC_ROOT}/src/core2/gc/section.c" secsrc)
string(REGEX REPLACE "//[^\n]*" "" secsrc "${secsrc}")
string(REGEX MATCH "MapInfo D_8036B810\\[[^]]*\\] *={(.*)};" _ "${secsrc}")
set(sec_body "${CMAKE_MATCH_1}")
string(REGEX MATCHALL "{[ \t\r\n]*MAP_([0-9A-Fa-f]+)_[A-Za-z0-9_]+,[ \t\r\n]*LEVEL_([0-9A-Fa-f]+)_"
       map_rows "${sec_body}")
set(rows "")
set(map_level_rows "")
foreach(row IN LISTS map_rows)
  string(REGEX MATCH "MAP_([0-9A-Fa-f]+)_[A-Za-z0-9_]+,[ \t\r\n]*LEVEL_([0-9A-Fa-f]+)_" _ "${row}")
  string(TOUPPER "${CMAKE_MATCH_2}" lvl)
  trim_hex(map_hex "${CMAKE_MATCH_1}")
  pad_hex(key "${CMAKE_MATCH_1}")
  list(APPEND map_level_rows "${key}|    { 0x${map_hex}, 0x${lvl} },")
  if(NOT DEFINED lvl2ov_${lvl})
    continue()
  endif()
  list(APPEND rows "${key}|    { 0x${map_hex}, 0x${lvl2ov_${lvl}} },")
endforeach()
emit_unique_rows("${OUT_DIR}/MapOverlays.inc" rows n_mapov)
emit_unique_rows("${OUT_DIR}/MapLevels.inc" map_level_rows n_maplvl)

message(STATUS "editor tables: ${n_names} actor names, ${n_models} actor models, ${n_levels} levels, ${n_level_enum} level ids, ${n_spawn} spawnables, ${n_mapov} map overlays, ${n_maplvl} map levels, ${n_exits} exits, ${n_warp_names} warps, ${n_warp_dests} destinations, ${n_sky} skyboxes")
