if(NOT SRC_ROOT OR NOT OUT_DIR)
  message(FATAL_ERROR "GenTables.cmake needs -DSRC_ROOT=<repo> -DOUT_DIR=<dir>")
endif()

file(MAKE_DIRECTORY "${OUT_DIR}")

function(trim_hex out hex)
  string(TOUPPER "${hex}" hex)
  string(REGEX REPLACE "^0+([0-9A-F])" "\\1" hex "${hex}")
  set(${out} "${hex}" PARENT_SCOPE)
endfunction()

function(pad_hex out hex)
  string(TOUPPER "${hex}" hex)
  string(LENGTH "${hex}" len)
  while(len LESS 4)
    set(hex "0${hex}")
    math(EXPR len "${len} + 1")
  endwhile()
  set(${out} "${hex}" PARENT_SCOPE)
endfunction()

function(write_if_changed path content)
  set(old "")
  if(EXISTS "${path}")
    file(READ "${path}" old)
  endif()
  if(NOT old STREQUAL content)
    file(WRITE "${path}" "${content}")
  endif()
endfunction()

file(READ "${SRC_ROOT}/include/enums.h" enums)
string(REGEX MATCH "typedef enum actor_e[^{]*{([^}]*)}" _ "${enums}")
set(actor_body "${CMAKE_MATCH_1}")
string(REGEX MATCHALL "ACTOR_[0-9A-Fa-f]+_[A-Za-z0-9_]+" actor_names "${actor_body}")

set(rows "")
set(out "")
set(last "")
set(count 0)
foreach(name IN LISTS actor_names)
  string(REGEX REPLACE "^ACTOR_([0-9A-Fa-f]+)_(.+)$" "\\1" hex "${name}")
  string(REGEX REPLACE "^ACTOR_([0-9A-Fa-f]+)_(.+)$" "\\2" tail "${name}")
  pad_hex(key "${hex}")
  string(TOUPPER "${hex}" hex)
  list(APPEND rows "${key}|    {0x${hex}, \"${tail}\"},")
endforeach()
list(SORT rows)
list(REMOVE_DUPLICATES rows)

foreach(row IN LISTS rows)
  string(REGEX REPLACE "^([0-9A-F]+)\\|(.*)$" "\\1" key "${row}")
  string(REGEX REPLACE "^([0-9A-F]+)\\|(.*)$" "\\2" line "${row}")
  if(NOT key STREQUAL last)
    set(last "${key}")
    math(EXPR count "${count} + 1")
    string(APPEND out "${line}\n")
  endif()
endforeach()
write_if_changed("${OUT_DIR}/ActorNames.inc" "${out}")
set(n_names ${count})

function(token_id out tok)
  string(STRIP "${tok}" tok)
  if(tok MATCHES "^(ACTOR|ASSET|MARKER)_([0-9A-Fa-f]+)_")
    set(${out} "${CMAKE_MATCH_2}" PARENT_SCOPE)
  elseif(tok MATCHES "^0[xX]([0-9A-Fa-f]+)$")
    set(${out} "${CMAKE_MATCH_1}" PARENT_SCOPE)
  elseif(tok MATCHES "^[0-9]+$")
    math(EXPR v "${tok}" OUTPUT_FORMAT HEXADECIMAL)
    string(REGEX REPLACE "^0[xX]" "" v "${v}")
    set(${out} "${v}" PARENT_SCOPE)
  else()
    set(${out} "" PARENT_SCOPE)
  endif()
endfunction()

file(GLOB_RECURSE csrc "${SRC_ROOT}/src/*.c")
set(rows "")
set(out "")
set(last "")
set(count 0)
set(tok "[ \t\r\n]*([A-Za-z0-9_]+)[ \t\r\n]*")
foreach(f IN LISTS csrc)
  file(READ "${f}" text)
  if(NOT text MATCHES "ActorInfo")
    continue()
  endif()
  string(REGEX REPLACE "//[^\n]*" "" text "${text}")
  string(REGEX REPLACE "/\\*[^*]*\\*+([^/*][^*]*\\*+)*/" "" text "${text}")
  string(REGEX MATCHALL "ActorInfo[ \t\r\n]+[A-Za-z0-9_]+[ \t\r\n]*=[ \t\r\n]*{${tok},${tok},${tok},"
         infos "${text}")
  foreach(info IN LISTS infos)
    string(REGEX MATCH "{${tok},${tok},${tok},$" _ "${info}")
    token_id(actor "${CMAKE_MATCH_2}")
    token_id(model "${CMAKE_MATCH_3}")
    if(actor STREQUAL "" OR model STREQUAL "" OR model STREQUAL "0")
      continue()
    endif()
    pad_hex(key "${actor}")
    trim_hex(actor "${actor}")
    trim_hex(model "${model}")
    list(APPEND rows "${key}|    {0x${actor}, 0x${model}},")
  endforeach()
endforeach()
list(SORT rows)
list(REMOVE_DUPLICATES rows)

foreach(row IN LISTS rows)
  string(REGEX REPLACE "^([0-9A-F]+)\\|(.*)$" "\\1" key "${row}")
  string(REGEX REPLACE "^([0-9A-F]+)\\|(.*)$" "\\2" line "${row}")
  if(NOT key STREQUAL last)
    set(last "${key}")
    math(EXPR count "${count} + 1")
    string(APPEND out "${line}\n")
  endif()
endforeach()
write_if_changed("${OUT_DIR}/ActorModels.inc" "${out}")
set(n_models ${count})

file(READ "${SRC_ROOT}/src/core2/map/mapModel.c" mapmodel)
string(REGEX REPLACE "//[^\n]*" "" mapmodel "${mapmodel}")
string(REGEX MATCH "MapModelDescription D_8036ABE0\\[\\] = {(.*)};" _ "${mapmodel}")
set(table_body "${CMAKE_MATCH_1}")
string(REGEX MATCHALL "{MAP_([0-9A-Fa-f]+)_([A-Za-z0-9_]+),[ \t\r\n]*(ASSET_[0-9A-Fa-f]+_[A-Za-z0-9_]+|0)[ \t\r\n]*,[ \t\r\n]*(ASSET_[0-9A-Fa-f]+_[A-Za-z0-9_]+|0)"
       level_rows "${table_body}")
set(out "")
set(count 0)
foreach(row IN LISTS level_rows)
  string(REGEX MATCH "{MAP_([0-9A-Fa-f]+)_([A-Za-z0-9_]+),[ \t\r\n]*(ASSET_[0-9A-Fa-f]+_[A-Za-z0-9_]+|0)[ \t\r\n]*,[ \t\r\n]*(ASSET_[0-9A-Fa-f]+_[A-Za-z0-9_]+|0)" _ "${row}")
  set(map_hex "${CMAKE_MATCH_1}")
  set(map_name "${CMAKE_MATCH_2}")
  token_id(opa "${CMAKE_MATCH_3}")
  token_id(xlu "${CMAKE_MATCH_4}")
  if(opa STREQUAL "" OR opa STREQUAL "0")
    continue()
  endif()
  if(xlu STREQUAL "")
    set(xlu "0")
  endif()
  trim_hex(map_hex "${map_hex}")
  trim_hex(opa "${opa}")
  trim_hex(xlu "${xlu}")
  math(EXPR count "${count} + 1")
  string(APPEND out "    { 0x${map_hex}, \"${map_name}\", 0x${opa}, 0x${xlu} },\n")
endforeach()
write_if_changed("${OUT_DIR}/LevelModels.inc" "${out}")

message(STATUS "editor tables: ${n_names} actor names, ${n_models} actor models, ${count} levels")
