if(NOT SRC_ROOT OR NOT OUT_DIR)
  message(FATAL_ERROR "GenTables.cmake needs -DSRC_ROOT=<repo> -DOUT_DIR=<dir>")
endif()

file(MAKE_DIRECTORY "${OUT_DIR}")

function(trim_hex out hex)
  string(TOUPPER "${hex}" hex)
  string(REGEX REPLACE "^0+([0-9A-F])" "\\1" hex "${hex}")
  set(${out} "${hex}" PARENT_SCOPE)
endfunction()

function(pad_hex out hex)
  string(TOUPPER "${hex}" hex)
  string(LENGTH "${hex}" len)
  while(len LESS 4)
    set(hex "0${hex}")
    math(EXPR len "${len} + 1")
  endwhile()
  set(${out} "${hex}" PARENT_SCOPE)
endfunction()

function(write_if_changed path content)
  set(old "")
  if(EXISTS "${path}")
    file(READ "${path}" old)
  endif()
  if(NOT old STREQUAL content)
    file(WRITE "${path}" "${content}")
  endif()
endfunction()

# Rows are "KEY|line". Sorted by key, one line per key, the first wins.
function(emit_unique_rows path rows_var count_var)
  set(rows "${${rows_var}}")
  list(SORT rows)
  list(REMOVE_DUPLICATES rows)
  set(out "")
  set(last "")
  set(count 0)
  foreach(row IN LISTS rows)
    string(REGEX REPLACE "^([0-9A-F]+)\\|(.*)$" "\\1" key "${row}")
    string(REGEX REPLACE "^([0-9A-F]+)\\|(.*)$" "\\2" line "${row}")
    if(NOT key STREQUAL last)
      set(last "${key}")
      math(EXPR count "${count} + 1")
      string(APPEND out "${line}\n")
    endif()
  endforeach()
  write_if_changed("${path}" "${out}")
  set(${count_var} ${count} PARENT_SCOPE)
endfunction()

file(READ "${SRC_ROOT}/include/enums.h" enums)
string(REGEX MATCH "typedef enum actor_e[^{]*{([^}]*)}" _ "${enums}")
set(actor_body "${CMAKE_MATCH_1}")
string(REGEX MATCHALL "ACTOR_[0-9A-Fa-f]+_[A-Za-z0-9_]+" actor_names "${actor_body}")

set(rows "")
foreach(name IN LISTS actor_names)
  string(REGEX REPLACE "^ACTOR_([0-9A-Fa-f]+)_(.+)$" "\\1" hex "${name}")
  string(REGEX REPLACE "^ACTOR_([0-9A-Fa-f]+)_(.+)$" "\\2" tail "${name}")
  pad_hex(key "${hex}")
  string(TOUPPER "${hex}" hex)
  list(APPEND rows "${key}|    {0x${hex}, \"${tail}\"},")
endforeach()
emit_unique_rows("${OUT_DIR}/ActorNames.inc" rows n_names)

function(token_id out tok)
  string(STRIP "${tok}" tok)
  if(tok MATCHES "^(ACTOR|ASSET|MARKER)_([0-9A-Fa-f]+)_")
    set(${out} "${CMAKE_MATCH_2}" PARENT_SCOPE)
  elseif(tok MATCHES "^0[xX]([0-9A-Fa-f]+)$")
    set(${out} "${CMAKE_MATCH_1}" PARENT_SCOPE)
  elseif(tok MATCHES "^[0-9]+$")
    math(EXPR v "${tok}" OUTPUT_FORMAT HEXADECIMAL)
    string(REGEX REPLACE "^0[xX]" "" v "${v}")
    set(${out} "${v}" PARENT_SCOPE)
  else()
    set(${out} "" PARENT_SCOPE)
  endif()
endfunction()

file(GLOB_RECURSE csrc "${SRC_ROOT}/src/*.c")
set(rows "")
set(tok "[ \t\r\n]*([A-Za-z0-9_]+)[ \t\r\n]*")
foreach(f IN LISTS csrc)
  file(READ "${f}" text)
  if(NOT text MATCHES "ActorInfo")
    continue()
  endif()
  string(REGEX REPLACE "//[^\n]*" "" text "${text}")
  string(REGEX REPLACE "/\\*[^*]*\\*+([^/*][^*]*\\*+)*/" "" text "${text}")
  string(REGEX MATCHALL "ActorInfo[ \t\r\n]+[A-Za-z0-9_]+[ \t\r\n]*=[ \t\r\n]*{${tok},${tok},${tok},"
         infos "${text}")
  foreach(info IN LISTS infos)
    string(REGEX MATCH "ActorInfo[ \t\r\n]+([A-Za-z0-9_]+)" _ "${info}")
    set(sym "${CMAKE_MATCH_1}")
    string(REGEX MATCH "{${tok},${tok},${tok},$" _ "${info}")
    token_id(actor "${CMAKE_MATCH_2}")
    token_id(model "${CMAKE_MATCH_3}")
    if(actor STREQUAL "")
      continue()
    endif()
    trim_hex(actor_trimmed "${actor}")
    set(aid_${sym} "${actor_trimmed}")
    if(model STREQUAL "")
      continue()
    endif()
    pad_hex(key "${actor}")
    trim_hex(model "${model}")
    list(APPEND rows "${key}|    {0x${actor_trimmed}, 0x${model}},")
  endforeach()
endforeach()
emit_unique_rows("${OUT_DIR}/ActorModels.inc" rows n_models)

file(READ "${SRC_ROOT}/src/core2/map/mapModel.c" mapmodel)
string(REGEX REPLACE "//[^\n]*" "" mapmodel "${mapmodel}")
string(REGEX MATCH "MapModelDescription D_8036ABE0\\[\\] = {(.*)};" _ "${mapmodel}")
set(table_body "${CMAKE_MATCH_1}")
string(REGEX MATCHALL "{MAP_([0-9A-Fa-f]+)_([A-Za-z0-9_]+),[ \t\r\n]*(ASSET_[0-9A-Fa-f]+_[A-Za-z0-9_]+|0)[ \t\r\n]*,[ \t\r\n]*(ASSET_[0-9A-Fa-f]+_[A-Za-z0-9_]+|0)"
       level_rows "${table_body}")
set(out "")
set(count 0)
foreach(row IN LISTS level_rows)
  string(REGEX MATCH "{MAP_([0-9A-Fa-f]+)_([A-Za-z0-9_]+),[ \t\r\n]*(ASSET_[0-9A-Fa-f]+_[A-Za-z0-9_]+|0)[ \t\r\n]*,[ \t\r\n]*(ASSET_[0-9A-Fa-f]+_[A-Za-z0-9_]+|0)" _ "${row}")
  set(map_hex "${CMAKE_MATCH_1}")
  set(map_name "${CMAKE_MATCH_2}")
  token_id(opa "${CMAKE_MATCH_3}")
  token_id(xlu "${CMAKE_MATCH_4}")
  if(opa STREQUAL "" OR opa STREQUAL "0")
    continue()
  endif()
  if(xlu STREQUAL "")
    set(xlu "0")
  endif()
  trim_hex(map_hex "${map_hex}")
  trim_hex(opa "${opa}")
  trim_hex(xlu "${xlu}")
  math(EXPR count "${count} + 1")
  string(APPEND out "    { 0x${map_hex}, \"${map_name}\", 0x${opa}, 0x${xlu} },\n")
endforeach()
write_if_changed("${OUT_DIR}/LevelModels.inc" "${out}")
set(n_levels ${count})
macro(collect_spawn_adds text_var overlay)
  string(REGEX MATCHALL "spawnableActorList_add[A-Za-z]*[ \t\r\n]*\\([ \t\r\n]*&[ \t\r\n]*[A-Za-z0-9_]+"
         adds "${${text_var}}")
  foreach(add IN LISTS adds)
    string(REGEX MATCH "&[ \t\r\n]*([A-Za-z0-9_]+)$" _ "${add}")
    set(sym "${CMAKE_MATCH_1}")
    if(DEFINED aid_${sym})
      pad_hex(key "${aid_${sym}}")
      list(APPEND spawn_rows "${overlay}${key}|    { 0x${overlay}, 0x${aid_${sym}} },")
    else()
      message(WARNING "editor tables: no ActorInfo found for spawnable '${sym}'")
    endif()
  endforeach()
endmacro()

set(spawn_rows "")
file(READ "${SRC_ROOT}/src/core2/spawnqueue.c" sq)
string(REGEX REPLACE "//[^\n]*" "" sq "${sq}")
string(REGEX REPLACE "/\\*[^*]*\\*+([^/*][^*]*\\*+)*/" "" sq "${sq}")
string(FIND "${sq}" "case OVERLAY_9_SNOW:" sq_cut)
if(sq_cut EQUAL -1)
  collect_spawn_adds(sq 0)
else()
  string(SUBSTRING "${sq}" 0 ${sq_cut} sq_common)
  string(SUBSTRING "${sq}" ${sq_cut} -1 sq_fp)
  collect_spawn_adds(sq_common 0)
  collect_spawn_adds(sq_fp 9)
endif()

# Overlay-specific spawn queues
foreach(pair IN ITEMS
    "CC/ccspawnqueue.c;2"
    "MMM/mmmspawnqueue.c;3"
    "GV/gvspawnqueue.c;4"
    "TTC/actor_spawninit.c;5"
    "MM/mmspawnqueue.c;6"
    "BGS/bgsspawnqueue.c;7"
    "RBB/rbbspawnqueue.c;8"
    "FP/fpspawnqueue.c;9"
    "CCW/ccwspawnqueue.c;A"
    "SM/smspawnqueue.c;B"
    "cutscenes/cutscenesspawnqueue.c;C"
    "lair/lairspawnqueue.c;D"
    "fight/fight.c;E")
  list(GET pair 0 rel)
  list(GET pair 1 ov)
  file(READ "${SRC_ROOT}/src/${rel}" text)
  string(REGEX REPLACE "//[^\n]*" "" text "${text}")
  string(REGEX REPLACE "/\\*[^*]*\\*+([^/*][^*]*\\*+)*/" "" text "${text}")
  collect_spawn_adds(text ${ov})
endforeach()

emit_unique_rows("${OUT_DIR}/SpawnSets.inc" spawn_rows n_spawn)
file(READ "${SRC_ROOT}/src/core2/map/overlay.c" ovsrc)
string(REGEX REPLACE "//[^\n]*" "" ovsrc "${ovsrc}")
string(REGEX MATCHALL "{[ \t\r\n]*LEVEL_([0-9A-Fa-f]+)_[A-Za-z0-9_]+,[ \t\r\n]*OVERLAY_([0-9A-Fa-f]+)_"
       ov_rows "${ovsrc}")
foreach(row IN LISTS ov_rows)
  string(REGEX MATCH "LEVEL_([0-9A-Fa-f]+)_[A-Za-z0-9_]+,[ \t\r\n]*OVERLAY_([0-9A-Fa-f]+)_" _ "${row}")
  string(TOUPPER "${CMAKE_MATCH_1}" lvl)
  string(TOUPPER "${CMAKE_MATCH_2}" ov)
  set(lvl2ov_${lvl} "${ov}")
endforeach()

file(READ "${SRC_ROOT}/src/core2/gc/section.c" secsrc)
string(REGEX REPLACE "//[^\n]*" "" secsrc "${secsrc}")
string(REGEX MATCH "MapInfo D_8036B810\\[[^]]*\\] *={(.*)};" _ "${secsrc}")
set(sec_body "${CMAKE_MATCH_1}")
string(REGEX MATCHALL "{[ \t\r\n]*MAP_([0-9A-Fa-f]+)_[A-Za-z0-9_]+,[ \t\r\n]*LEVEL_([0-9A-Fa-f]+)_"
       map_rows "${sec_body}")
set(rows "")
foreach(row IN LISTS map_rows)
  string(REGEX MATCH "MAP_([0-9A-Fa-f]+)_[A-Za-z0-9_]+,[ \t\r\n]*LEVEL_([0-9A-Fa-f]+)_" _ "${row}")
  string(TOUPPER "${CMAKE_MATCH_2}" lvl)
  if(NOT DEFINED lvl2ov_${lvl})
    continue()
  endif()
  trim_hex(map_hex "${CMAKE_MATCH_1}")
  pad_hex(key "${CMAKE_MATCH_1}")
  list(APPEND rows "${key}|    { 0x${map_hex}, 0x${lvl2ov_${lvl}} },")
endforeach()
emit_unique_rows("${OUT_DIR}/MapOverlays.inc" rows n_mapov)

message(STATUS "editor tables: ${n_names} actor names, ${n_models} actor models, ${n_levels} levels, ${n_spawn} spawnables, ${n_mapov} map overlays")
